### ISSUE TITLE
c is not defined

### ISSUE THREAD

**Issue by mrtdmrmrt** [81-javascript-bootcamp/bootcamp-homepage#9]
function outer() { 
  let counter = 0; 
  function incrementCounter() { 
    counter++; 
  } 
  return c; 
} 
const myFunction = outer(); 
myFunction() // 1 
myFunction() // 2
outer fonksiyonun içinde return c yazılmış sanırım return incrementCounter olacaktı.

**Comment by NisanTarhan** [comment]
incrementCounter olması lazım aslında düzeltelim. Teşekkürler
